// =============================================================================
// MTS TELECOM - Demo Mode Data Fixtures
// =============================================================================
// Billcom Consulting - PFE 2026
// =============================================================================
//
// OBJECTIF:
// Données réalistes pré-chargées pour le mode démo soutenance.
// Chaque dataset reflète un scénario Telecom crédible :
// - Clients entreprise marocains
// - Services FTTH / 4G / VoIP / Cloud
// - Tickets variés avec SLA, priorités, assignations
// - Incidents actifs et résolus
// - Dashboard stats cohérents
//
// CONVENTIONS:
// - Dates relatives à "maintenant" pour rester frais
// - IDs stables (1-999) pour que les liens fonctionnent
// - Labels FR alignés sur les enums backend
//
// =============================================================================

import {
  TicketStatus,
  TicketPriority,
  TicketCategory,
  ServiceStatus,
  ServiceCategory,
  ServiceCriticality,
  UserRole,
  IncidentStatus,
  Severity,
  IncidentImpact,
} from "../types";
import type {
  Ticket,
  TelecomService,
  Incident,
  DashboardStats,
  AgentPerformance,
  Client,
  UserResponse,
  AuditLog,
  Notification,
  SlaPolicy,
  PageResponse,
} from "../types";

// =============================================================================
// HELPERS
// =============================================================================

/** Date relative : maintenant - N heures */
const hoursAgo = (h: number): string => new Date(Date.now() - h * 3600_000).toISOString();

/** Date relative : maintenant - N jours */
const daysAgo = (d: number): string => new Date(Date.now() - d * 86400_000).toISOString();

/** Date relative : maintenant + N heures (deadlines) */
const hoursFromNow = (h: number): string => new Date(Date.now() + h * 3600_000).toISOString();

/** Wrapper pour PageResponse */
function page<T>(items: T[], totalElements?: number): PageResponse<T> {
  const total = totalElements ?? items.length;
  return {
    content: items,
    totalElements: total,
    totalPages: Math.ceil(total / 20),
    size: 20,
    number: 0,
    first: true,
    last: items.length < 20,
    empty: items.length === 0,
  };
}

// =============================================================================
// UTILISATEURS DÉMO
// =============================================================================

export const DEMO_USERS: UserResponse[] = [
  {
    id: 1,
    email: "admin@mts-telecom.ma",
    firstName: "Mohammed",
    lastName: "Benali",
    fullName: "Mohammed Benali",
    role: UserRole.ADMIN,
    phone: "+212 6 12 34 56 78",
    isActive: true,
    createdAt: daysAgo(365),
    lastLoginAt: hoursAgo(0),
  },
  {
    id: 2,
    email: "sara.manager@mts-telecom.ma",
    firstName: "Sara",
    lastName: "El Fassi",
    fullName: "Sara El Fassi",
    role: UserRole.MANAGER,
    phone: "+212 6 23 45 67 89",
    isActive: true,
    createdAt: daysAgo(300),
    lastLoginAt: hoursAgo(2),
  },
  {
    id: 3,
    email: "karim.agent@mts-telecom.ma",
    firstName: "Karim",
    lastName: "Ziani",
    fullName: "Karim Ziani",
    role: UserRole.AGENT,
    phone: "+212 6 34 56 78 90",
    isActive: true,
    createdAt: daysAgo(200),
    lastLoginAt: hoursAgo(1),
  },
  {
    id: 4,
    email: "layla.agent@mts-telecom.ma",
    firstName: "Layla",
    lastName: "Amrani",
    fullName: "Layla Amrani",
    role: UserRole.AGENT,
    phone: "+212 6 45 67 89 01",
    isActive: true,
    createdAt: daysAgo(180),
    lastLoginAt: hoursAgo(3),
  },
  {
    id: 5,
    email: "contact@maroc-industries.ma",
    firstName: "Omar",
    lastName: "Khalil",
    fullName: "Omar Khalil",
    role: UserRole.CLIENT,
    phone: "+212 5 22 33 44 55",
    isActive: true,
    createdAt: daysAgo(150),
    lastLoginAt: hoursAgo(6),
    clientInfo: { id: 1, clientCode: "CLI-2025-001", companyName: "Maroc Industries SA" },
  },
  {
    id: 6,
    email: "dsi@atlas-logistics.ma",
    firstName: "Fatima",
    lastName: "Berrada",
    fullName: "Fatima Berrada",
    role: UserRole.CLIENT,
    phone: "+212 5 37 44 55 66",
    isActive: true,
    createdAt: daysAgo(120),
    lastLoginAt: daysAgo(1),
    clientInfo: { id: 2, clientCode: "CLI-2025-002", companyName: "Atlas Logistics" },
  },
  {
    id: 7,
    email: "it@casablanca-hotel.ma",
    firstName: "Youssef",
    lastName: "Tazi",
    fullName: "Youssef Tazi",
    role: UserRole.CLIENT,
    phone: "+212 5 22 88 99 00",
    isActive: true,
    createdAt: daysAgo(90),
    lastLoginAt: daysAgo(2),
    clientInfo: { id: 3, clientCode: "CLI-2025-003", companyName: "Casablanca Grand Hôtel" },
  },
];

// =============================================================================
// CLIENTS DÉMO
// =============================================================================

export const DEMO_CLIENTS: Client[] = [
  {
    id: 1,
    clientCode: "CLI-2025-001",
    companyName: "Maroc Industries SA",
    address: "Zone Industrielle, Lot 42, Casablanca",
    userId: 5,
    userEmail: "contact@maroc-industries.ma",
    userFullName: "Omar Khalil",
    userPhone: "+212 5 22 33 44 55",
    isActive: true,
    ticketCount: 8,
    createdAt: daysAgo(150),
  },
  {
    id: 2,
    clientCode: "CLI-2025-002",
    companyName: "Atlas Logistics",
    address: "Avenue Hassan II, Rabat",
    userId: 6,
    userEmail: "dsi@atlas-logistics.ma",
    userFullName: "Fatima Berrada",
    userPhone: "+212 5 37 44 55 66",
    isActive: true,
    ticketCount: 5,
    createdAt: daysAgo(120),
  },
  {
    id: 3,
    clientCode: "CLI-2025-003",
    companyName: "Casablanca Grand Hôtel",
    address: "Boulevard d'Anfa, Casablanca",
    userId: 7,
    userEmail: "it@casablanca-hotel.ma",
    userFullName: "Youssef Tazi",
    userPhone: "+212 5 22 88 99 00",
    isActive: true,
    ticketCount: 3,
    createdAt: daysAgo(90),
  },
];

// =============================================================================
// SERVICES TÉLÉCOM DÉMO
// =============================================================================

export const DEMO_SERVICES: TelecomService[] = [
  {
    id: 1,
    name: "Fibre FTTH Entreprise",
    category: ServiceCategory.NETWORK,
    categoryLabel: "Réseau",
    description:
      "Accès Internet fibre optique dédié pour entreprises (débit garanti 100 Mbps symétrique)",
    isActive: true,
    status: ServiceStatus.UP,
    statusLabel: "Opérationnel",
    availabilityPct: 99.95,
    avgLatencyMs: 3,
    criticality: ServiceCriticality.CRITICAL,
    criticalityLabel: "Critique",
    ticketCount: 4,
    activeIncidentCount: 0,
    createdAt: daysAgo(365),
  },
  {
    id: 2,
    name: "4G LTE Pro",
    category: ServiceCategory.NETWORK,
    categoryLabel: "Réseau",
    description: "Connectivité mobile 4G/LTE avec APN dédié pour flotte entreprise",
    isActive: true,
    status: ServiceStatus.DEGRADED,
    statusLabel: "Dégradé",
    availabilityPct: 97.2,
    avgLatencyMs: 28,
    criticality: ServiceCriticality.HIGH,
    criticalityLabel: "Haute",
    ticketCount: 5,
    activeIncidentCount: 1,
    createdAt: daysAgo(300),
  },
  {
    id: 3,
    name: "VoIP SIP Trunk",
    category: ServiceCategory.NETWORK,
    categoryLabel: "Réseau",
    description: "Téléphonie IP multi-canaux SIP pour standard téléphonique entreprise",
    isActive: true,
    status: ServiceStatus.UP,
    statusLabel: "Opérationnel",
    availabilityPct: 99.8,
    avgLatencyMs: 12,
    criticality: ServiceCriticality.HIGH,
    criticalityLabel: "Haute",
    ticketCount: 2,
    activeIncidentCount: 0,
    createdAt: daysAgo(250),
  },
  {
    id: 4,
    name: "Cloud Hosting Maroc",
    category: ServiceCategory.INFRA,
    categoryLabel: "Infrastructure",
    description: "Hébergement cloud privé dans le datacenter de Casablanca (ISO 27001)",
    isActive: true,
    status: ServiceStatus.UP,
    statusLabel: "Opérationnel",
    availabilityPct: 99.99,
    avgLatencyMs: 1,
    criticality: ServiceCriticality.CRITICAL,
    criticalityLabel: "Critique",
    ticketCount: 2,
    activeIncidentCount: 0,
    createdAt: daysAgo(200),
  },
  {
    id: 5,
    name: "CRM Telecom Suite",
    category: ServiceCategory.CRM,
    categoryLabel: "CRM",
    description: "Suite CRM intégrée pour la gestion des abonnés et facturation",
    isActive: true,
    status: ServiceStatus.UP,
    statusLabel: "Opérationnel",
    availabilityPct: 99.6,
    avgLatencyMs: 45,
    criticality: ServiceCriticality.MEDIUM,
    criticalityLabel: "Moyenne",
    ticketCount: 1,
    activeIncidentCount: 0,
    createdAt: daysAgo(180),
  },
  {
    id: 6,
    name: "Facturation & Billing",
    category: ServiceCategory.BILLING,
    categoryLabel: "Facturation",
    description: "Plateforme de facturation et de gestion des abonnements",
    isActive: true,
    status: ServiceStatus.MAINTENANCE,
    statusLabel: "Maintenance",
    availabilityPct: 95.0,
    avgLatencyMs: 120,
    criticality: ServiceCriticality.MEDIUM,
    criticalityLabel: "Moyenne",
    ticketCount: 2,
    activeIncidentCount: 0,
    createdAt: daysAgo(160),
  },
];

// =============================================================================
// TICKETS DÉMO (scénarios variés et réalistes)
// =============================================================================

export const DEMO_TICKETS: Ticket[] = [
  // --- Tickets actifs ---
  {
    id: 1,
    ticketNumber: "TKT-2026-0042",
    title: "Perte de connectivité fibre site principal Casablanca",
    description:
      "Coupure totale du lien fibre depuis ce matin 8h30. Le routeur CPE montre les LEDs Rx/Tx éteintes. Aucun trafic ne passe. Impact: 200 employés sans accès Internet ni VPN.",
    status: TicketStatus.IN_PROGRESS,
    statusLabel: "En cours",
    priority: TicketPriority.CRITICAL,
    priorityLabel: "Critique",
    category: TicketCategory.PANNE,
    categoryLabel: "Panne",
    clientId: 1,
    clientName: "Omar Khalil",
    clientCode: "CLI-2025-001",
    clientCompanyName: "Maroc Industries SA",
    serviceId: 1,
    serviceName: "Fibre FTTH Entreprise",
    createdById: 5,
    createdByName: "Omar Khalil",
    assignedToId: 3,
    assignedToName: "Karim Ziani",
    slaHours: 4,
    deadline: hoursFromNow(2),
    breachedSla: false,
    slaPercentage: 72,
    slaWarning: true,
    slaRemainingMinutes: 120,
    createdAt: hoursAgo(2),
    commentCount: 3,
    allowedTransitions: [TicketStatus.PENDING, TicketStatus.ESCALATED, TicketStatus.RESOLVED],
  },
  {
    id: 2,
    ticketNumber: "TKT-2026-0041",
    title: "Latence élevée sur le réseau 4G – zone industrielle Aïn Sebaâ",
    description:
      "Nos techniciens terrain constatent des latences supérieures à 200ms sur la 4G depuis 2 jours. Les applications métier mobiles deviennent inutilisables.",
    status: TicketStatus.ASSIGNED,
    statusLabel: "Assigné",
    priority: TicketPriority.HIGH,
    priorityLabel: "Haute",
    category: TicketCategory.PANNE,
    categoryLabel: "Panne",
    clientId: 1,
    clientName: "Omar Khalil",
    clientCode: "CLI-2025-001",
    clientCompanyName: "Maroc Industries SA",
    serviceId: 2,
    serviceName: "4G LTE Pro",
    createdById: 5,
    createdByName: "Omar Khalil",
    assignedToId: 4,
    assignedToName: "Layla Amrani",
    slaHours: 8,
    deadline: hoursFromNow(5),
    breachedSla: false,
    slaPercentage: 45,
    slaRemainingMinutes: 300,
    createdAt: hoursAgo(3),
    commentCount: 1,
    allowedTransitions: [TicketStatus.IN_PROGRESS, TicketStatus.PENDING, TicketStatus.ESCALATED],
  },
  {
    id: 3,
    ticketNumber: "TKT-2026-0040",
    title: "Demande d'augmentation de bande passante fibre – site Rabat",
    description:
      "Suite à l'ouverture de notre nouveau département, nous avons besoin de passer de 100 Mbps à 200 Mbps symétrique sur le site de Rabat.",
    status: TicketStatus.PENDING,
    statusLabel: "En attente client",
    priority: TicketPriority.MEDIUM,
    priorityLabel: "Moyenne",
    category: TicketCategory.EVOLUTION,
    categoryLabel: "Évolution",
    clientId: 2,
    clientName: "Fatima Berrada",
    clientCode: "CLI-2025-002",
    clientCompanyName: "Atlas Logistics",
    serviceId: 1,
    serviceName: "Fibre FTTH Entreprise",
    createdById: 6,
    createdByName: "Fatima Berrada",
    assignedToId: 3,
    assignedToName: "Karim Ziani",
    slaHours: 24,
    deadline: hoursFromNow(18),
    breachedSla: false,
    slaPercentage: 30,
    slaRemainingMinutes: 1080,
    createdAt: hoursAgo(6),
    commentCount: 2,
    allowedTransitions: [TicketStatus.IN_PROGRESS, TicketStatus.RESOLVED],
  },
  {
    id: 4,
    ticketNumber: "TKT-2026-0039",
    title: "Problème de qualité VoIP – écho et coupures",
    description:
      "Depuis la mise à jour du central téléphonique, certains appels présentent de l'écho et des coupures aléatoires. Affecte environ 30% des appels sortants.",
    status: TicketStatus.ESCALATED,
    statusLabel: "Escaladé",
    priority: TicketPriority.HIGH,
    priorityLabel: "Haute",
    category: TicketCategory.PANNE,
    categoryLabel: "Panne",
    clientId: 3,
    clientName: "Youssef Tazi",
    clientCode: "CLI-2025-003",
    clientCompanyName: "Casablanca Grand Hôtel",
    serviceId: 3,
    serviceName: "VoIP SIP Trunk",
    createdById: 7,
    createdByName: "Youssef Tazi",
    assignedToId: 3,
    assignedToName: "Karim Ziani",
    slaHours: 8,
    deadline: hoursAgo(1),
    breachedSla: true,
    slaPercentage: 112,
    slaRemainingMinutes: -60,
    createdAt: hoursAgo(10),
    commentCount: 5,
    allowedTransitions: [TicketStatus.IN_PROGRESS, TicketStatus.RESOLVED],
  },
  {
    id: 5,
    ticketNumber: "TKT-2026-0038",
    title: "Création de 10 nouvelles lignes SIP pour extension centre d'appels",
    description:
      "Notre centre d'appels s'agrandit. Nous avons besoin de 10 canaux SIP supplémentaires avec les numéros en 05 22.",
    status: TicketStatus.NEW,
    statusLabel: "Nouveau",
    priority: TicketPriority.LOW,
    priorityLabel: "Basse",
    category: TicketCategory.DEMANDE,
    categoryLabel: "Demande",
    clientId: 3,
    clientName: "Youssef Tazi",
    clientCode: "CLI-2025-003",
    clientCompanyName: "Casablanca Grand Hôtel",
    serviceId: 3,
    serviceName: "VoIP SIP Trunk",
    createdById: 7,
    createdByName: "Youssef Tazi",
    assignedToId: undefined,
    assignedToName: undefined,
    slaHours: 48,
    deadline: hoursFromNow(40),
    breachedSla: false,
    slaPercentage: 15,
    slaRemainingMinutes: 2400,
    createdAt: hoursAgo(8),
    commentCount: 0,
    allowedTransitions: [TicketStatus.ASSIGNED],
  },

  // --- Tickets résolus / fermés (historique) ---
  {
    id: 6,
    ticketNumber: "TKT-2026-0037",
    title: "Migration serveur vers Cloud Hosting – Atlas Logistics",
    description:
      "Migration complète de l'infrastructure on-premise vers Cloud Hosting Maroc. 3 VMs + base de données PostgreSQL.",
    status: TicketStatus.RESOLVED,
    statusLabel: "Résolu",
    priority: TicketPriority.MEDIUM,
    priorityLabel: "Moyenne",
    category: TicketCategory.EVOLUTION,
    categoryLabel: "Évolution",
    clientId: 2,
    clientName: "Fatima Berrada",
    clientCode: "CLI-2025-002",
    clientCompanyName: "Atlas Logistics",
    serviceId: 4,
    serviceName: "Cloud Hosting Maroc",
    createdById: 6,
    createdByName: "Fatima Berrada",
    assignedToId: 4,
    assignedToName: "Layla Amrani",
    slaHours: 24,
    deadline: daysAgo(1),
    breachedSla: false,
    slaPercentage: 80,
    resolution:
      "Migration effectuée avec succès. 3 VMs provisionnées, DB restaurée. Tests de charge OK.",
    createdAt: daysAgo(3),
    resolvedAt: daysAgo(1),
    commentCount: 8,
    slaRemainingMinutes: 0,
    allowedTransitions: [TicketStatus.CLOSED],
  },
  {
    id: 7,
    ticketNumber: "TKT-2026-0036",
    title: "Facturation incorrecte – double prélèvement février",
    description:
      "Nous avons été prélevés 2 fois pour le mois de février sur le service Fibre FTTH.",
    status: TicketStatus.CLOSED,
    statusLabel: "Fermé",
    priority: TicketPriority.HIGH,
    priorityLabel: "Haute",
    category: TicketCategory.AUTRE,
    categoryLabel: "Autre",
    clientId: 1,
    clientName: "Omar Khalil",
    clientCode: "CLI-2025-001",
    clientCompanyName: "Maroc Industries SA",
    serviceId: 6,
    serviceName: "Facturation & Billing",
    createdById: 5,
    createdByName: "Omar Khalil",
    assignedToId: 3,
    assignedToName: "Karim Ziani",
    slaHours: 8,
    deadline: daysAgo(4),
    breachedSla: false,
    slaPercentage: 60,
    resolution:
      "Note de crédit émise. Remboursement du 2e prélèvement effectué sous 5 jours ouvrés.",
    createdAt: daysAgo(5),
    resolvedAt: daysAgo(4),
    closedAt: daysAgo(3),
    commentCount: 4,
    slaRemainingMinutes: 0,
    allowedTransitions: [],
  },
  {
    id: 8,
    ticketNumber: "TKT-2026-0035",
    title: "Demande de rapport de disponibilité mensuel",
    description:
      "Merci de nous fournir le rapport SLA de disponibilité de tous nos services pour le mois de janvier 2026.",
    status: TicketStatus.CLOSED,
    statusLabel: "Fermé",
    priority: TicketPriority.LOW,
    priorityLabel: "Basse",
    category: TicketCategory.DEMANDE,
    categoryLabel: "Demande",
    clientId: 2,
    clientName: "Fatima Berrada",
    clientCode: "CLI-2025-002",
    clientCompanyName: "Atlas Logistics",
    serviceId: 5,
    serviceName: "CRM Telecom Suite",
    createdById: 6,
    createdByName: "Fatima Berrada",
    assignedToId: 4,
    assignedToName: "Layla Amrani",
    slaHours: 48,
    deadline: daysAgo(6),
    breachedSla: false,
    slaPercentage: 40,
    resolution: "Rapport PDF envoyé au client par email. Taux de disponibilité global : 99.7%.",
    createdAt: daysAgo(8),
    resolvedAt: daysAgo(7),
    closedAt: daysAgo(6),
    commentCount: 2,
    slaRemainingMinutes: 0,
    allowedTransitions: [],
  },
];

// =============================================================================
// INCIDENTS DÉMO
// =============================================================================

export const DEMO_INCIDENTS: Incident[] = [
  {
    id: 1,
    incidentNumber: "INC-2026-0012",
    title: "Dégradation performances réseau 4G – région Casablanca",
    description:
      "Augmentation de la latence de 15ms à 200ms+ sur les antennes du secteur Aïn Sebaâ / Sidi Bernoussi. Impact sur 3 clients entreprise. Cause suspectée : saturation backhaul.",
    severity: Severity.MAJOR,
    severityLabel: "Majeur",
    impact: IncidentImpact.PARTIAL,
    impactLabel: "Partiel",
    status: IncidentStatus.IN_PROGRESS,
    statusLabel: "En cours",
    serviceId: 2,
    serviceName: "4G LTE Pro",
    commanderId: 2,
    commanderName: "Sara El Fassi",
    ticketIds: [2],
    ticketNumbers: ["TKT-2026-0041"],
    affectedServiceIds: [2],
    affectedServiceNames: ["4G LTE Pro"],
    timelineCount: 4,
    startedAt: hoursAgo(6),
    createdAt: hoursAgo(6),
  },
  {
    id: 2,
    incidentNumber: "INC-2026-0011",
    title: "Maintenance planifiée plateforme Billing",
    description:
      "Mise à jour de la plateforme de facturation vers la version 4.2. Fenêtre de maintenance : 02h00 – 06h00. Aucun impact sur les autres services.",
    severity: Severity.LOW,
    severityLabel: "Faible",
    impact: IncidentImpact.LOCALIZED,
    impactLabel: "Localisé",
    status: IncidentStatus.OPEN,
    statusLabel: "Ouvert",
    serviceId: 6,
    serviceName: "Facturation & Billing",
    commanderId: 2,
    commanderName: "Sara El Fassi",
    affectedServiceIds: [6],
    affectedServiceNames: ["Facturation & Billing"],
    timelineCount: 1,
    startedAt: hoursAgo(2),
    createdAt: hoursAgo(2),
  },
  {
    id: 3,
    incidentNumber: "INC-2026-0010",
    title: "Panne switch core datacenter – Rétabli",
    description:
      "Panne du switch core Nexus 9000 dans le datacenter Casa. Basculement automatique sur le switch redondant en 12 secondes. Root cause: module alimentation défaillant.",
    severity: Severity.CRITICAL,
    severityLabel: "Critique",
    impact: IncidentImpact.MAJOR,
    impactLabel: "Majeur",
    status: IncidentStatus.RESOLVED,
    statusLabel: "Résolu",
    serviceId: 4,
    serviceName: "Cloud Hosting Maroc",
    commanderId: 1,
    commanderName: "Mohammed Benali",
    affectedServiceIds: [1, 4],
    affectedServiceNames: ["Fibre FTTH Entreprise", "Cloud Hosting Maroc"],
    timelineCount: 8,
    startedAt: daysAgo(3),
    resolvedAt: daysAgo(3),
    cause: "Module alimentation PSU-2 défaillant sur switch Nexus 9000. Remplacé sous garantie.",
    hasPostMortem: true,
    postMortem:
      "Le basculement automatique a fonctionné en 12s. Recommandation : ajouter monitoring SNMP sur les PSU.",
    createdAt: daysAgo(3),
  },
];

// =============================================================================
// DASHBOARD STATS DÉMO
// =============================================================================

export const DEMO_DASHBOARD_STATS: DashboardStats = {
  totalTickets: 8,
  activeTickets: 5,
  resolvedThisMonth: 3,
  slaBreachedCount: 1,
  averageResolutionTimeHours: 7.2,
  averageResolutionHours: 7.2,
  slaComplianceRate: 87.5,
  ticketsByStatus: {
    NEW: 1,
    ASSIGNED: 1,
    IN_PROGRESS: 1,
    PENDING: 1,
    ESCALATED: 1,
    RESOLVED: 1,
    CLOSED: 2,
    CANCELLED: 0,
  },
  ticketsByPriority: {
    CRITICAL: 1,
    HIGH: 3,
    MEDIUM: 2,
    LOW: 2,
  },
  ticketsByService: {
    "Fibre FTTH Entreprise": 2,
    "4G LTE Pro": 1,
    "VoIP SIP Trunk": 2,
    "Cloud Hosting Maroc": 1,
    "CRM Telecom Suite": 1,
    "Facturation & Billing": 1,
  },
  agentStats: [
    {
      agentId: 3,
      agentName: "Karim Ziani",
      assignedTickets: 3,
      resolvedTickets: 1,
      averageResolutionTimeHours: 6.6,
    },
    {
      agentId: 4,
      agentName: "Layla Amrani",
      assignedTickets: 3,
      resolvedTickets: 2,
      averageResolutionTimeHours: 7.8,
    },
  ],
  criticalCount: 1,
  highCount: 3,
  mediumCount: 2,
  lowCount: 2,
  unassignedCount: 1,
  createdToday: 5,
  resolvedToday: 1,
  trendLast7Days: Array.from({ length: 7 }, (_, i) => ({
    date: new Date(Date.now() - (6 - i) * 86400_000).toISOString().split("T")[0],
    created: [1, 0, 1, 0, 1, 0, 5][i],
    resolved: [0, 1, 0, 1, 0, 0, 1][i],
    active: [5, 4, 5, 4, 5, 5, 5][i],
  })),
  previousPeriodSnapshot: {
    resolvedThisMonth: 2,
    activeTickets: 6,
    totalTickets: 7,
    slaBreachedCount: 1,
  },
};

// =============================================================================
// AGENT PERFORMANCE DÉMO
// =============================================================================

export const DEMO_AGENT_PERFORMANCE: AgentPerformance[] = [
  {
    agentId: 3,
    agentName: "Karim Ziani",
    assignedTickets: 3,
    resolvedTickets: 1,
    averageResolutionHours: 6.6,
    slaComplianceRate: 88.9,
  },
  {
    agentId: 4,
    agentName: "Layla Amrani",
    assignedTickets: 3,
    resolvedTickets: 2,
    averageResolutionHours: 7.8,
    slaComplianceRate: 90.0,
  },
];

// =============================================================================
// AUDIT LOGS DÉMO
// =============================================================================

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: 1,
    timestamp: hoursAgo(0.5),
    userName: "Karim Ziani",
    userEmail: "karim.agent@mts-telecom.ma",
    userId: 3,
    action: "TICKET_STATUS_CHANGED",
    actionLabel: "Statut modifié",
    actionCategory: "Tickets",
    entityType: "TICKET",
    entityId: 1,
    entityName: "TKT-2026-0042",
    description: "Statut changé de ASSIGNED → IN_PROGRESS",
    oldValue: "ASSIGNED",
    newValue: "IN_PROGRESS",
    ipAddress: "192.168.1.42",
    systemAction: false,
  },
  {
    id: 2,
    timestamp: hoursAgo(2),
    userName: "Sara El Fassi",
    userEmail: "sara.manager@mts-telecom.ma",
    userId: 2,
    action: "TICKET_ASSIGNED",
    actionLabel: "Ticket assigné",
    actionCategory: "Tickets",
    entityType: "TICKET",
    entityId: 1,
    entityName: "TKT-2026-0042",
    description: "Ticket assigné à Karim Ziani",
    newValue: "Karim Ziani",
    ipAddress: "192.168.1.10",
    systemAction: false,
  },
  {
    id: 3,
    timestamp: hoursAgo(2),
    userName: "Omar Khalil",
    userEmail: "contact@maroc-industries.ma",
    userId: 5,
    action: "TICKET_CREATED",
    actionLabel: "Ticket créé",
    actionCategory: "Tickets",
    entityType: "TICKET",
    entityId: 1,
    entityName: "TKT-2026-0042",
    description: "Nouveau ticket : Perte de connectivité fibre site principal",
    ipAddress: "41.92.23.156",
    systemAction: false,
  },
  {
    id: 4,
    timestamp: hoursAgo(6),
    userName: null,
    userEmail: null,
    userId: null,
    action: "SLA_ESCALATION_TRIGGERED",
    actionLabel: "Escalade SLA déclenchée",
    actionCategory: "SLA",
    entityType: "TICKET",
    entityId: 4,
    entityName: "TKT-2026-0039",
    description: "SLA dépassé — ticket escaladé automatiquement (niveau 1)",
    ipAddress: null,
    systemAction: true,
  },
  {
    id: 5,
    timestamp: hoursAgo(8),
    userName: "Mohammed Benali",
    userEmail: "admin@mts-telecom.ma",
    userId: 1,
    action: "SERVICE_STATUS_CHANGED",
    actionLabel: "Statut service modifié",
    actionCategory: "Services",
    entityType: "SERVICE",
    entityId: 6,
    entityName: "Facturation & Billing",
    description: "Statut changé de UP → MAINTENANCE pour mise à jour v4.2",
    oldValue: "UP",
    newValue: "MAINTENANCE",
    ipAddress: "192.168.1.1",
    systemAction: false,
  },
  {
    id: 6,
    timestamp: daysAgo(1),
    userName: "Mohammed Benali",
    userEmail: "admin@mts-telecom.ma",
    userId: 1,
    action: "USER_CREATED",
    actionLabel: "Utilisateur créé",
    actionCategory: "Administration",
    entityType: "USER",
    entityId: 7,
    entityName: "Youssef Tazi",
    description: "Nouvel utilisateur client créé pour Casablanca Grand Hôtel",
    ipAddress: "192.168.1.1",
    systemAction: false,
  },
];

// =============================================================================
// NOTIFICATIONS DÉMO
// =============================================================================

export const DEMO_NOTIFICATIONS: Notification[] = [
  {
    id: 1,
    title: "Ticket critique assigné",
    message: "Le ticket TKT-2026-0042 (Perte de connectivité fibre) vous a été assigné.",
    type: "TICKET_ASSIGNED",
    referenceType: "TICKET",
    referenceId: 1,
    referencePath: "/tickets",
    isRead: false,
    createdAt: hoursAgo(2),
    isUrgent: true,
  },
  {
    id: 2,
    title: "SLA en danger",
    message: "Le ticket TKT-2026-0042 atteint 72% du SLA. Résolution attendue dans 2h.",
    type: "SLA_WARNING",
    referenceType: "TICKET",
    referenceId: 1,
    referencePath: "/tickets",
    isRead: false,
    createdAt: hoursAgo(1),
    isUrgent: true,
  },
  {
    id: 3,
    title: "SLA dépassé",
    message: "Le ticket TKT-2026-0039 (VoIP – écho et coupures) a dépassé son SLA de 8h.",
    type: "SLA_BREACH",
    referenceType: "TICKET",
    referenceId: 4,
    referencePath: "/tickets",
    isRead: true,
    readAt: hoursAgo(0.5),
    createdAt: hoursAgo(1),
    isUrgent: false,
  },
  {
    id: 4,
    title: "Incident déclaré",
    message: "Nouvel incident INC-2026-0012 : Dégradation 4G région Casablanca.",
    type: "INCIDENT_CREATED",
    referenceType: "INCIDENT",
    referenceId: 1,
    referencePath: "/incidents/1",
    isRead: true,
    readAt: hoursAgo(5),
    createdAt: hoursAgo(6),
    isUrgent: false,
  },
];

// =============================================================================
// SLA POLICIES DÉMO
// =============================================================================

export const DEMO_SLA_POLICIES: SlaPolicy[] = [
  {
    id: 1,
    name: "SLA Critique",
    description: "Tickets critiques — résolution sous 4h, première réponse sous 30min",
    priority: "CRITICAL" as SlaPolicy["priority"],
    responseTimeHours: 0.5,
    resolutionTimeHours: 4,
    active: true,
    createdAt: daysAgo(365),
  },
  {
    id: 2,
    name: "SLA Haute Priorité",
    description: "Tickets haute priorité — résolution sous 8h",
    priority: "HIGH" as SlaPolicy["priority"],
    responseTimeHours: 1,
    resolutionTimeHours: 8,
    active: true,
    createdAt: daysAgo(365),
  },
  {
    id: 3,
    name: "SLA Standard",
    description: "Tickets priorité moyenne — résolution sous 24h",
    priority: "MEDIUM" as SlaPolicy["priority"],
    responseTimeHours: 4,
    resolutionTimeHours: 24,
    active: true,
    createdAt: daysAgo(365),
  },
  {
    id: 4,
    name: "SLA Basse Priorité",
    description: "Tickets basse priorité — résolution sous 48h",
    priority: "LOW" as SlaPolicy["priority"],
    responseTimeHours: 8,
    resolutionTimeHours: 48,
    active: true,
    createdAt: daysAgo(365),
  },
];

// =============================================================================
// EXPORT GROUPÉ
// =============================================================================

/** Toutes les données démo regroupées, prêtes pour le routeur démo. */
export const DEMO_DATA = {
  users: DEMO_USERS,
  clients: DEMO_CLIENTS,
  services: DEMO_SERVICES,
  tickets: DEMO_TICKETS,
  incidents: DEMO_INCIDENTS,
  dashboardStats: DEMO_DASHBOARD_STATS,
  agentPerformance: DEMO_AGENT_PERFORMANCE,
  auditLogs: DEMO_AUDIT_LOGS,
  notifications: DEMO_NOTIFICATIONS,
  slaPolicies: DEMO_SLA_POLICIES,

  // Helpers pré-paginés
  ticketsPage: page(DEMO_TICKETS),
  servicesPage: page(DEMO_SERVICES),
  auditLogsPage: page(DEMO_AUDIT_LOGS),
} as const;
